pipeline {
    agent {
        docker {
            // image 'maven:3-alpine'
            image 'maven:latest'
            args '-v /Users/david/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package -X'
            }
        }
        // stage('Test') {
        //     steps {
        //         sh 'mvn test'
        //     }
        //     post {
        //         always {
        //             junit 'target/surefire-reports/*.xml'
        //         }
        //     }
        // }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('docker build'){
            steps {
                sh 'docker build -t david_hello -f Dockerfile'
            }
        }




    }
}
